# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - build
  - test
  - coverage
  - release


variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

  RELEASE_REGISTRY: docker.io
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-amqp-trigger-metrics

  PYTEST_COV_MODULE: os2mo_amqp_trigger_metrics
  PYTEST_COV_FAIL_UNDER: 0

include:
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/autopub.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/pre-commit.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-build.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-release.v1.yml
  - project: labs/salt-automation
    ref: master
    file: gitlab-ci-templates/python/pytest.v1.yml


# This is a workaround for a bug causing detached pipelines on MRs
# See: https://gitlab.com/gitlab-org/gitlab/-/issues/34756
#      https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
