# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

version: "3.9"
services:
  consumer:
    build: .
    container_name: amqp_trigger_metrics
    environment:
      AMQP_HOST: 192.168.1.234
      AMQP_PASSWORD: guest
    ports:
      - 8000:8000
